github.com:
    oauth_token: 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
    user: HiraethEcho
    git_protocol: ssh
    users:
        HiraethEcho:
            oauth_token: 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
